/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MainImport } from './routes/_main'
import { Route as IndexImport } from './routes/index'
import { Route as MainKoIndexImport } from './routes/_main/ko/index'
import { Route as MainEnIndexImport } from './routes/_main/en/index'
import { Route as DocsKoDocs350IndexImport } from './routes/_docs/ko.docs/3_5_0/index'
import { Route as DocsKoDocs350TutorialImport } from './routes/_docs/ko.docs/3_5_0/tutorial'
import { Route as DocsKoDocs350DeepDiveImport } from './routes/_docs/ko.docs/3_5_0/deep-dive'

// Create/Update Routes

const MainRoute = MainImport.update({
  id: '/_main',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MainKoIndexRoute = MainKoIndexImport.update({
  id: '/ko/',
  path: '/ko/',
  getParentRoute: () => MainRoute,
} as any)

const MainEnIndexRoute = MainEnIndexImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => MainRoute,
} as any)

const DocsKoDocs350IndexRoute = DocsKoDocs350IndexImport.update({
  id: '/_docs/ko/docs/3_5_0/',
  path: '/ko/docs/3_5_0/',
  getParentRoute: () => rootRoute,
} as any)

const DocsKoDocs350TutorialRoute = DocsKoDocs350TutorialImport.update({
  id: '/_docs/ko/docs/3_5_0/tutorial',
  path: '/ko/docs/3_5_0/tutorial',
  getParentRoute: () => rootRoute,
} as any)

const DocsKoDocs350DeepDiveRoute = DocsKoDocs350DeepDiveImport.update({
  id: '/_docs/ko/docs/3_5_0/deep-dive',
  path: '/ko/docs/3_5_0/deep-dive',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainImport
      parentRoute: typeof rootRoute
    }
    '/_main/en/': {
      id: '/_main/en/'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof MainEnIndexImport
      parentRoute: typeof MainImport
    }
    '/_main/ko/': {
      id: '/_main/ko/'
      path: '/ko'
      fullPath: '/ko'
      preLoaderRoute: typeof MainKoIndexImport
      parentRoute: typeof MainImport
    }
    '/_docs/ko/docs/3_5_0/deep-dive': {
      id: '/_docs/ko/docs/3_5_0/deep-dive'
      path: '/ko/docs/3_5_0/deep-dive'
      fullPath: '/ko/docs/3_5_0/deep-dive'
      preLoaderRoute: typeof DocsKoDocs350DeepDiveImport
      parentRoute: typeof rootRoute
    }
    '/_docs/ko/docs/3_5_0/tutorial': {
      id: '/_docs/ko/docs/3_5_0/tutorial'
      path: '/ko/docs/3_5_0/tutorial'
      fullPath: '/ko/docs/3_5_0/tutorial'
      preLoaderRoute: typeof DocsKoDocs350TutorialImport
      parentRoute: typeof rootRoute
    }
    '/_docs/ko/docs/3_5_0/': {
      id: '/_docs/ko/docs/3_5_0/'
      path: '/ko/docs/3_5_0'
      fullPath: '/ko/docs/3_5_0'
      preLoaderRoute: typeof DocsKoDocs350IndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface MainRouteChildren {
  MainEnIndexRoute: typeof MainEnIndexRoute
  MainKoIndexRoute: typeof MainKoIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainEnIndexRoute: MainEnIndexRoute,
  MainKoIndexRoute: MainKoIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof MainRouteWithChildren
  '/en': typeof MainEnIndexRoute
  '/ko': typeof MainKoIndexRoute
  '/ko/docs/3_5_0/deep-dive': typeof DocsKoDocs350DeepDiveRoute
  '/ko/docs/3_5_0/tutorial': typeof DocsKoDocs350TutorialRoute
  '/ko/docs/3_5_0': typeof DocsKoDocs350IndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof MainRouteWithChildren
  '/en': typeof MainEnIndexRoute
  '/ko': typeof MainKoIndexRoute
  '/ko/docs/3_5_0/deep-dive': typeof DocsKoDocs350DeepDiveRoute
  '/ko/docs/3_5_0/tutorial': typeof DocsKoDocs350TutorialRoute
  '/ko/docs/3_5_0': typeof DocsKoDocs350IndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_main': typeof MainRouteWithChildren
  '/_main/en/': typeof MainEnIndexRoute
  '/_main/ko/': typeof MainKoIndexRoute
  '/_docs/ko/docs/3_5_0/deep-dive': typeof DocsKoDocs350DeepDiveRoute
  '/_docs/ko/docs/3_5_0/tutorial': typeof DocsKoDocs350TutorialRoute
  '/_docs/ko/docs/3_5_0/': typeof DocsKoDocs350IndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/en'
    | '/ko'
    | '/ko/docs/3_5_0/deep-dive'
    | '/ko/docs/3_5_0/tutorial'
    | '/ko/docs/3_5_0'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/en'
    | '/ko'
    | '/ko/docs/3_5_0/deep-dive'
    | '/ko/docs/3_5_0/tutorial'
    | '/ko/docs/3_5_0'
  id:
    | '__root__'
    | '/'
    | '/_main'
    | '/_main/en/'
    | '/_main/ko/'
    | '/_docs/ko/docs/3_5_0/deep-dive'
    | '/_docs/ko/docs/3_5_0/tutorial'
    | '/_docs/ko/docs/3_5_0/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainRoute: typeof MainRouteWithChildren
  DocsKoDocs350DeepDiveRoute: typeof DocsKoDocs350DeepDiveRoute
  DocsKoDocs350TutorialRoute: typeof DocsKoDocs350TutorialRoute
  DocsKoDocs350IndexRoute: typeof DocsKoDocs350IndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainRoute: MainRouteWithChildren,
  DocsKoDocs350DeepDiveRoute: DocsKoDocs350DeepDiveRoute,
  DocsKoDocs350TutorialRoute: DocsKoDocs350TutorialRoute,
  DocsKoDocs350IndexRoute: DocsKoDocs350IndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_main",
        "/_docs/ko/docs/3_5_0/deep-dive",
        "/_docs/ko/docs/3_5_0/tutorial",
        "/_docs/ko/docs/3_5_0/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_main": {
      "filePath": "_main.tsx",
      "children": [
        "/_main/en/",
        "/_main/ko/"
      ]
    },
    "/_main/en/": {
      "filePath": "_main/en/index.tsx",
      "parent": "/_main"
    },
    "/_main/ko/": {
      "filePath": "_main/ko/index.tsx",
      "parent": "/_main"
    },
    "/_docs/ko/docs/3_5_0/deep-dive": {
      "filePath": "_docs/ko.docs/3_5_0/deep-dive.tsx"
    },
    "/_docs/ko/docs/3_5_0/tutorial": {
      "filePath": "_docs/ko.docs/3_5_0/tutorial.tsx"
    },
    "/_docs/ko/docs/3_5_0/": {
      "filePath": "_docs/ko.docs/3_5_0/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
