/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MainImport } from './routes/_main'
import { Route as IndexImport } from './routes/index'
import { Route as MainKoIndexImport } from './routes/_main/ko/index'
import { Route as MainEnIndexImport } from './routes/_main/en/index'
import { Route as DocsKoDocsIndexImport } from './routes/_docs/ko.docs/index'
import { Route as DocsEnDocsIndexImport } from './routes/_docs/en.docs/index'
import { Route as DocsKoDocs35Import } from './routes/_docs/ko.docs/3_5'
import { Route as DocsEnDocs35Import } from './routes/_docs/en.docs/3_5'
import { Route as DocsKoDocs35IndexImport } from './routes/_docs/ko.docs/3_5/index'
import { Route as DocsEnDocs35IndexImport } from './routes/_docs/en.docs/3_5/index'
import { Route as DocsKoDocs35TutorialImport } from './routes/_docs/ko.docs/3_5/tutorial'
import { Route as DocsKoDocs35DeepDiveImport } from './routes/_docs/ko.docs/3_5/deep-dive'
import { Route as DocsEnDocs35TutorialImport } from './routes/_docs/en.docs/3_5/tutorial'
import { Route as DocsEnDocs35DeepDiveImport } from './routes/_docs/en.docs/3_5/deep-dive'

// Create/Update Routes

const MainRoute = MainImport.update({
  id: '/_main',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MainKoIndexRoute = MainKoIndexImport.update({
  id: '/ko/',
  path: '/ko/',
  getParentRoute: () => MainRoute,
} as any)

const MainEnIndexRoute = MainEnIndexImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => MainRoute,
} as any)

const DocsKoDocsIndexRoute = DocsKoDocsIndexImport.update({
  id: '/_docs/ko/docs/',
  path: '/ko/docs/',
  getParentRoute: () => rootRoute,
} as any)

const DocsEnDocsIndexRoute = DocsEnDocsIndexImport.update({
  id: '/_docs/en/docs/',
  path: '/en/docs/',
  getParentRoute: () => rootRoute,
} as any)

const DocsKoDocs35Route = DocsKoDocs35Import.update({
  id: '/_docs/ko/docs/3_5',
  path: '/ko/docs/3_5',
  getParentRoute: () => rootRoute,
} as any)

const DocsEnDocs35Route = DocsEnDocs35Import.update({
  id: '/_docs/en/docs/3_5',
  path: '/en/docs/3_5',
  getParentRoute: () => rootRoute,
} as any)

const DocsKoDocs35IndexRoute = DocsKoDocs35IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsKoDocs35Route,
} as any)

const DocsEnDocs35IndexRoute = DocsEnDocs35IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsEnDocs35Route,
} as any)

const DocsKoDocs35TutorialRoute = DocsKoDocs35TutorialImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => DocsKoDocs35Route,
} as any)

const DocsKoDocs35DeepDiveRoute = DocsKoDocs35DeepDiveImport.update({
  id: '/deep-dive',
  path: '/deep-dive',
  getParentRoute: () => DocsKoDocs35Route,
} as any)

const DocsEnDocs35TutorialRoute = DocsEnDocs35TutorialImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => DocsEnDocs35Route,
} as any)

const DocsEnDocs35DeepDiveRoute = DocsEnDocs35DeepDiveImport.update({
  id: '/deep-dive',
  path: '/deep-dive',
  getParentRoute: () => DocsEnDocs35Route,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainImport
      parentRoute: typeof rootRoute
    }
    '/_main/en/': {
      id: '/_main/en/'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof MainEnIndexImport
      parentRoute: typeof MainImport
    }
    '/_main/ko/': {
      id: '/_main/ko/'
      path: '/ko'
      fullPath: '/ko'
      preLoaderRoute: typeof MainKoIndexImport
      parentRoute: typeof MainImport
    }
    '/_docs/en/docs/3_5': {
      id: '/_docs/en/docs/3_5'
      path: '/en/docs/3_5'
      fullPath: '/en/docs/3_5'
      preLoaderRoute: typeof DocsEnDocs35Import
      parentRoute: typeof rootRoute
    }
    '/_docs/ko/docs/3_5': {
      id: '/_docs/ko/docs/3_5'
      path: '/ko/docs/3_5'
      fullPath: '/ko/docs/3_5'
      preLoaderRoute: typeof DocsKoDocs35Import
      parentRoute: typeof rootRoute
    }
    '/_docs/en/docs/': {
      id: '/_docs/en/docs/'
      path: '/en/docs'
      fullPath: '/en/docs'
      preLoaderRoute: typeof DocsEnDocsIndexImport
      parentRoute: typeof rootRoute
    }
    '/_docs/ko/docs/': {
      id: '/_docs/ko/docs/'
      path: '/ko/docs'
      fullPath: '/ko/docs'
      preLoaderRoute: typeof DocsKoDocsIndexImport
      parentRoute: typeof rootRoute
    }
    '/_docs/en/docs/3_5/deep-dive': {
      id: '/_docs/en/docs/3_5/deep-dive'
      path: '/deep-dive'
      fullPath: '/en/docs/3_5/deep-dive'
      preLoaderRoute: typeof DocsEnDocs35DeepDiveImport
      parentRoute: typeof DocsEnDocs35Import
    }
    '/_docs/en/docs/3_5/tutorial': {
      id: '/_docs/en/docs/3_5/tutorial'
      path: '/tutorial'
      fullPath: '/en/docs/3_5/tutorial'
      preLoaderRoute: typeof DocsEnDocs35TutorialImport
      parentRoute: typeof DocsEnDocs35Import
    }
    '/_docs/ko/docs/3_5/deep-dive': {
      id: '/_docs/ko/docs/3_5/deep-dive'
      path: '/deep-dive'
      fullPath: '/ko/docs/3_5/deep-dive'
      preLoaderRoute: typeof DocsKoDocs35DeepDiveImport
      parentRoute: typeof DocsKoDocs35Import
    }
    '/_docs/ko/docs/3_5/tutorial': {
      id: '/_docs/ko/docs/3_5/tutorial'
      path: '/tutorial'
      fullPath: '/ko/docs/3_5/tutorial'
      preLoaderRoute: typeof DocsKoDocs35TutorialImport
      parentRoute: typeof DocsKoDocs35Import
    }
    '/_docs/en/docs/3_5/': {
      id: '/_docs/en/docs/3_5/'
      path: '/'
      fullPath: '/en/docs/3_5/'
      preLoaderRoute: typeof DocsEnDocs35IndexImport
      parentRoute: typeof DocsEnDocs35Import
    }
    '/_docs/ko/docs/3_5/': {
      id: '/_docs/ko/docs/3_5/'
      path: '/'
      fullPath: '/ko/docs/3_5/'
      preLoaderRoute: typeof DocsKoDocs35IndexImport
      parentRoute: typeof DocsKoDocs35Import
    }
  }
}

// Create and export the route tree

interface MainRouteChildren {
  MainEnIndexRoute: typeof MainEnIndexRoute
  MainKoIndexRoute: typeof MainKoIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainEnIndexRoute: MainEnIndexRoute,
  MainKoIndexRoute: MainKoIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

interface DocsEnDocs35RouteChildren {
  DocsEnDocs35DeepDiveRoute: typeof DocsEnDocs35DeepDiveRoute
  DocsEnDocs35TutorialRoute: typeof DocsEnDocs35TutorialRoute
  DocsEnDocs35IndexRoute: typeof DocsEnDocs35IndexRoute
}

const DocsEnDocs35RouteChildren: DocsEnDocs35RouteChildren = {
  DocsEnDocs35DeepDiveRoute: DocsEnDocs35DeepDiveRoute,
  DocsEnDocs35TutorialRoute: DocsEnDocs35TutorialRoute,
  DocsEnDocs35IndexRoute: DocsEnDocs35IndexRoute,
}

const DocsEnDocs35RouteWithChildren = DocsEnDocs35Route._addFileChildren(
  DocsEnDocs35RouteChildren,
)

interface DocsKoDocs35RouteChildren {
  DocsKoDocs35DeepDiveRoute: typeof DocsKoDocs35DeepDiveRoute
  DocsKoDocs35TutorialRoute: typeof DocsKoDocs35TutorialRoute
  DocsKoDocs35IndexRoute: typeof DocsKoDocs35IndexRoute
}

const DocsKoDocs35RouteChildren: DocsKoDocs35RouteChildren = {
  DocsKoDocs35DeepDiveRoute: DocsKoDocs35DeepDiveRoute,
  DocsKoDocs35TutorialRoute: DocsKoDocs35TutorialRoute,
  DocsKoDocs35IndexRoute: DocsKoDocs35IndexRoute,
}

const DocsKoDocs35RouteWithChildren = DocsKoDocs35Route._addFileChildren(
  DocsKoDocs35RouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof MainRouteWithChildren
  '/en': typeof MainEnIndexRoute
  '/ko': typeof MainKoIndexRoute
  '/en/docs/3_5': typeof DocsEnDocs35RouteWithChildren
  '/ko/docs/3_5': typeof DocsKoDocs35RouteWithChildren
  '/en/docs': typeof DocsEnDocsIndexRoute
  '/ko/docs': typeof DocsKoDocsIndexRoute
  '/en/docs/3_5/deep-dive': typeof DocsEnDocs35DeepDiveRoute
  '/en/docs/3_5/tutorial': typeof DocsEnDocs35TutorialRoute
  '/ko/docs/3_5/deep-dive': typeof DocsKoDocs35DeepDiveRoute
  '/ko/docs/3_5/tutorial': typeof DocsKoDocs35TutorialRoute
  '/en/docs/3_5/': typeof DocsEnDocs35IndexRoute
  '/ko/docs/3_5/': typeof DocsKoDocs35IndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof MainRouteWithChildren
  '/en': typeof MainEnIndexRoute
  '/ko': typeof MainKoIndexRoute
  '/en/docs': typeof DocsEnDocsIndexRoute
  '/ko/docs': typeof DocsKoDocsIndexRoute
  '/en/docs/3_5/deep-dive': typeof DocsEnDocs35DeepDiveRoute
  '/en/docs/3_5/tutorial': typeof DocsEnDocs35TutorialRoute
  '/ko/docs/3_5/deep-dive': typeof DocsKoDocs35DeepDiveRoute
  '/ko/docs/3_5/tutorial': typeof DocsKoDocs35TutorialRoute
  '/en/docs/3_5': typeof DocsEnDocs35IndexRoute
  '/ko/docs/3_5': typeof DocsKoDocs35IndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_main': typeof MainRouteWithChildren
  '/_main/en/': typeof MainEnIndexRoute
  '/_main/ko/': typeof MainKoIndexRoute
  '/_docs/en/docs/3_5': typeof DocsEnDocs35RouteWithChildren
  '/_docs/ko/docs/3_5': typeof DocsKoDocs35RouteWithChildren
  '/_docs/en/docs/': typeof DocsEnDocsIndexRoute
  '/_docs/ko/docs/': typeof DocsKoDocsIndexRoute
  '/_docs/en/docs/3_5/deep-dive': typeof DocsEnDocs35DeepDiveRoute
  '/_docs/en/docs/3_5/tutorial': typeof DocsEnDocs35TutorialRoute
  '/_docs/ko/docs/3_5/deep-dive': typeof DocsKoDocs35DeepDiveRoute
  '/_docs/ko/docs/3_5/tutorial': typeof DocsKoDocs35TutorialRoute
  '/_docs/en/docs/3_5/': typeof DocsEnDocs35IndexRoute
  '/_docs/ko/docs/3_5/': typeof DocsKoDocs35IndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/en'
    | '/ko'
    | '/en/docs/3_5'
    | '/ko/docs/3_5'
    | '/en/docs'
    | '/ko/docs'
    | '/en/docs/3_5/deep-dive'
    | '/en/docs/3_5/tutorial'
    | '/ko/docs/3_5/deep-dive'
    | '/ko/docs/3_5/tutorial'
    | '/en/docs/3_5/'
    | '/ko/docs/3_5/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/en'
    | '/ko'
    | '/en/docs'
    | '/ko/docs'
    | '/en/docs/3_5/deep-dive'
    | '/en/docs/3_5/tutorial'
    | '/ko/docs/3_5/deep-dive'
    | '/ko/docs/3_5/tutorial'
    | '/en/docs/3_5'
    | '/ko/docs/3_5'
  id:
    | '__root__'
    | '/'
    | '/_main'
    | '/_main/en/'
    | '/_main/ko/'
    | '/_docs/en/docs/3_5'
    | '/_docs/ko/docs/3_5'
    | '/_docs/en/docs/'
    | '/_docs/ko/docs/'
    | '/_docs/en/docs/3_5/deep-dive'
    | '/_docs/en/docs/3_5/tutorial'
    | '/_docs/ko/docs/3_5/deep-dive'
    | '/_docs/ko/docs/3_5/tutorial'
    | '/_docs/en/docs/3_5/'
    | '/_docs/ko/docs/3_5/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainRoute: typeof MainRouteWithChildren
  DocsEnDocs35Route: typeof DocsEnDocs35RouteWithChildren
  DocsKoDocs35Route: typeof DocsKoDocs35RouteWithChildren
  DocsEnDocsIndexRoute: typeof DocsEnDocsIndexRoute
  DocsKoDocsIndexRoute: typeof DocsKoDocsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainRoute: MainRouteWithChildren,
  DocsEnDocs35Route: DocsEnDocs35RouteWithChildren,
  DocsKoDocs35Route: DocsKoDocs35RouteWithChildren,
  DocsEnDocsIndexRoute: DocsEnDocsIndexRoute,
  DocsKoDocsIndexRoute: DocsKoDocsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_main",
        "/_docs/en/docs/3_5",
        "/_docs/ko/docs/3_5",
        "/_docs/en/docs/",
        "/_docs/ko/docs/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_main": {
      "filePath": "_main.tsx",
      "children": [
        "/_main/en/",
        "/_main/ko/"
      ]
    },
    "/_main/en/": {
      "filePath": "_main/en/index.tsx",
      "parent": "/_main"
    },
    "/_main/ko/": {
      "filePath": "_main/ko/index.tsx",
      "parent": "/_main"
    },
    "/_docs/en/docs/3_5": {
      "filePath": "_docs/en.docs/3_5.tsx",
      "children": [
        "/_docs/en/docs/3_5/deep-dive",
        "/_docs/en/docs/3_5/tutorial",
        "/_docs/en/docs/3_5/"
      ]
    },
    "/_docs/ko/docs/3_5": {
      "filePath": "_docs/ko.docs/3_5.tsx",
      "children": [
        "/_docs/ko/docs/3_5/deep-dive",
        "/_docs/ko/docs/3_5/tutorial",
        "/_docs/ko/docs/3_5/"
      ]
    },
    "/_docs/en/docs/": {
      "filePath": "_docs/en.docs/index.tsx"
    },
    "/_docs/ko/docs/": {
      "filePath": "_docs/ko.docs/index.tsx"
    },
    "/_docs/en/docs/3_5/deep-dive": {
      "filePath": "_docs/en.docs/3_5/deep-dive.tsx",
      "parent": "/_docs/en/docs/3_5"
    },
    "/_docs/en/docs/3_5/tutorial": {
      "filePath": "_docs/en.docs/3_5/tutorial.tsx",
      "parent": "/_docs/en/docs/3_5"
    },
    "/_docs/ko/docs/3_5/deep-dive": {
      "filePath": "_docs/ko.docs/3_5/deep-dive.tsx",
      "parent": "/_docs/ko/docs/3_5"
    },
    "/_docs/ko/docs/3_5/tutorial": {
      "filePath": "_docs/ko.docs/3_5/tutorial.tsx",
      "parent": "/_docs/ko/docs/3_5"
    },
    "/_docs/en/docs/3_5/": {
      "filePath": "_docs/en.docs/3_5/index.tsx",
      "parent": "/_docs/en/docs/3_5"
    },
    "/_docs/ko/docs/3_5/": {
      "filePath": "_docs/ko.docs/3_5/index.tsx",
      "parent": "/_docs/ko/docs/3_5"
    }
  }
}
ROUTE_MANIFEST_END */
